### ISSUE TITLE
websafety 7

### ISSUE THREAD

**Issue by MrErr** [diladele/docker-websafety#11]
github says that the latest image is 7.0. In https://hub.docker.com/r/diladele/websafety/tags the latest tag is 6.4. Has the 7.0 image been uploaded to docker hub?

**Comment by ra-at-diladele-com** [comment]
Indeed, will try to push the build in several days.

**Comment by ra-at-diladele-com** [comment]
Sorry it took so long. The latest 7.0 with Squid 4.6 is now pushed as 7.0 tag into Docker Hub. Closing the issue.
