### ISSUE TITLE
 Is websafety now part of Squid's setup, or is it just an optional extension feature ?

### ISSUE THREAD

**Issue by marxenegls** [diladele/docker-websafety#14]
i'm having issues , none of which i had in previous version, i might add for 2years atleast.  
First of all i installed Squid on part D:/Squid i noticed in the conf.diladele that ssl-bump points to C:/progdata/Diladele/../..  for generated temp certs: 

"http_port 3128 ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB cert=/cygdrive/c/programdata/Diladele/DiladeleWebSafety/4.0/etc/myca.pem"

no such dir created , i assume because the websafety isn't installed and i'm hoping these config params wouldn't take effect unless it is also installed , right ?

does this mean that the websafety is now part of Squid's installation, or is it just an optional extension feature ?
 hence the 4 config files

# integration with Diladele Web Safety for Squid for Windows
icap_enable on
icap_preview_enable on
icap_preview_size 4096
icap_persistent_connections on
icap_send_client_ip on
icap_send_client_username on
icap_client_username_header X-Client-Username
icap_service_failure_limit -1
icap_service qlproxy1 reqmod_precache bypass=0 icap://127.0.0.1:1344/reqmod
icap_service qlproxy2 respmod_precache bypass=0 icap://127.0.0.1:1344/respmod
acl qlproxy_icap_edomains dstdomain "/cygdrive/c/programdata/Diladele/DiladeleWebSafety/4.0/etc/squid/icap_exclusions_domains.conf" 
acl qlproxy_icap_etypes rep_mime_type "/cygdrive/c/programdata/Diladele/DiladeleWebSafety/4.0/etc/squid/icap_exclusions_contenttypes.conf"
adaptation_access qlproxy1 deny qlproxy_icap_edomains
adaptation_access qlproxy2 deny qlproxy_icap_edomains
adaptation_access qlproxy2 deny qlproxy_icap_etypes
adaptation_access qlproxy1 allow all
adaptation_access qlproxy2 allow all

..  and i assume the new diladele websafety filters must be conflicting, possibly with my managed opendns setup  - i haven't yet tried debugging or checking logs . I thought i had fixed it by uninstalling and clearing out the previous  Squid\var ..\log ..\run folders but hellas not 

on the Docs site Websafety installation mentions;

"Fully configured versions of Web Safety can be quickly deployed as virtual appliance in VMware vSphere/ESXi, Microsoft Hyper-V, Azure and Amazon AWS. It is also possible to install it on your real hardware by following corresponding articles in the administrators guide."

features of websafety i.e icap server:

"ICAP Service is installed with Filtering Service. It includes an ICAP server that enables third-party proxies to communicate with Filtering Service."

"Filtering Service interacts with ICAP Service and Network Agent to respond to Internet requests passed from the proxy via ICAP."

**Comment by ra-at-diladele-com** [comment]
Unfortunately Web Safety only runs on Linux. It might be possible to have a Web Safety ICAP server run on Linux and squid on windows but it this case using a linux-only hyper-v machine would be much simpler. 

if you need a windows based web filter with ui please take a look at web filtering proxy (another project) - see https://webproxy.diladele.com/

**Comment by marxenegls** [comment]
Thanks for the quick reply
