### ISSUE TITLE
Please update Dockerfile to 6.2

### ISSUE THREAD

**Issue by henry-nicolas** [diladele/docker-websafety#8]

**Comment by ra-at-diladele-com** [comment]
Hello Henry, we will update the Docker after 6.2 release (it is now only in RC stage).

**Comment by henry-nicolas** [comment]
Hello, now that 6.2 is out, can you please kindly upgrade the Dockerfile ?

**Comment by ra-at-diladele-com** [comment]
Yes will do soon. Thanks!

**Comment by ra-at-diladele-com** [comment]
Done, it is now at docke hub and at 6.2
